### PR TITLE
Upgrade Yams dependency to 5.0.1

### PR DESCRIPTION
**Pull request by orj**
# 📝 Summary of Changes

Changes proposed in this pull request:

- Upgrades the Yams package to 5.0.1

# ⚠️ Items of Note

- #251 will need to be merged first and then this rebased off that.

# 🧐🗒 Reviewer Notes

## 🔨 How To Test

Test `asc` commands that load config from `Yaml` files.

### CODE REVIEW

**Comment by JamesW-iOS** [comment]
Could be possible I'm just using it wrong but it's erroring out when I try to sync user information from a YAML file.

##Command:
`asc users sync ./input.yml --input-format yaml --dry-run`
##input.yml:
```YAML
- username: me@thetrex.dev
  firstName: James
  lastName: TestLastName
  roles:
  - ADMIN
  - ACCOUNT_HOLDER
  provisioningAllowed: true
  allAppsVisible: true
```

Output:
```
## Dry run ##
Error: Expected single publisher output but received 0
```

**Comment by orj** [comment]
@JamesW-iOS Could also be that it doesn't work. :)

**Comment by orj** [comment]
@JamesW-iOS This bug isn't an issue with the Yaml library but rather with the rest of the code.

**Review by JamesW-iOS — APPROVED** [review]
Tried with the TestFlight syncing and the YAML parsing part worked

**Pull request merged**
