### PR TITLE
Ability to use capability: appleIdAuth

### PR DESCRIPTION
**Pull request by ptmt**
This adds ability to list, enable and disable the new capability.

Requires an update of SDK, which is sent here https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/121

### CODE REVIEW

**Comment by adamjcampbell** [comment]
Hey @ptmt thanks for your contribution. We're actually running off of a fork of the `appstoreconnect-swift-sdk` so that we can move faster if we so choose.

We have two paths here as I see it:
1. Wait until your PR is merged into `appstoreconnect-swift-sdk` and then we can pull the latest into our fork
2. Open a PR on our fork: https://github.com/ittybittyapps/appstoreconnect-swift-sdk and we can potentially get things moving more quickly

Depends on how urgently you need this change

**Comment by orj** [comment]
@adamjcampbell @ptmt's PR was merged into @AvdLee's repo upstream.  Perhaps we can bring this in now?

**Comment by ptmt** [comment]
Sorry for the silence. I somehow missed the email. The PR was merged rathe quickly to the upstream. Would be lovely to use it.

Thank you for the project! I use a local fork, with the some other changes, don't know yet how to bring all of them back, but will try eventually.I completely stopped using web browser for this.

**Comment by adamjcampbell** [comment]
@ptmt it's great that you've been able to make use of it!
If you have time to contribute back the features that are of use to you that'd also be excellent.
When I have some time I'll attempt to get this building and merged in.

**Review by orj — APPROVED** [review]
LGTM

**Pull request merged**
